apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dependencies.example.dependency-injector
spec:
  scope: Namespaced
  group: example.dependency-injector
  names:
    kind: Dependency
    plural: dependencies
    singular: dependency
    shortNames:
      - dep
      - deps
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
