---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.serviceAccount.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-role-cluster
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [example.dependency-injector]
    resources: [clusterkopfpeerings, dependencies]
    verbs: [list, watch, patch, get]
  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [events]
    verbs: [create, list, watch]
  - apiGroups: [example.dependency-injector]
    resources: [dependencies]
    verbs: [list, watch, update, delete, patch]
  - apiGroups: [""]
    resources: [pods, pods/status]
    verbs: [create, list, watch, update, patch]
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: [list, watch]    
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1, admissionregistration.k8s.io]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }}-role-cluster
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}